CREATE TABLE PERSON (
  ID varchar(100) NOT NULL,
  USERNAME varchar(45) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  UPDATED TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
  ID varchar(100) NOT NULL,
  NAME varchar(45) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  UPDATED TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PERSON_ROLE (
  PERSON_ID varchar(100) NOT NULL,
  ROLE_ID varchar(100) NOT NULL,
  CONSTRAINT PERSON_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
  CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
)
